language: node_js
node_js:
  - "node"

after_script:
  - gitbook build
  - cd ./_book
  - git init
  - git config usr.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - cp ../CNAME .
  - git add .
  - git commit -m "publish gitbook"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${P_BRANCH}

branchs:
  only:
    master